Added maxInstances & minInstances to cloudfunction config
Space48/cloud-seed pull request #56
Opened 2022-05-30 12:10 UTC by AndrewBarber

Closes issue #55

2022-05-30 12:19 UTC, S48-Mo commented on stacks/gcp/GcpStack.ts
> +      maxInstances: func.maxInstances ?? 0,
Why would the min have a default of 1 yet the max have a default of 1?

2022-05-30 12:20 UTC, S48-Mo requested changes
Why would the min have a default of 1 yet the max have a default of 0?

2022-05-30 12:55 UTC, AndrewBarber commented
> 



> Why would the min have a default of 1 yet the max have a default of 0?

Oops! I misread the line "enter a number greater than or equal to 1" on the [documentation](https://cloud.google.com/functions/docs/configuring/min-instances). Using 0 will clear and set to default, so you are correct.

Updated PR.

2022-05-30 15:10 UTC, seanpertet approved these changes

2022-05-30 15:10 UTC, seanpertet commented on types/runtime.ts
> +  maxInstances?: number | undefined;
no need to add `| undefined` at the end. The question mark after the key means that the property could be undefined

2022-05-30 15:37 UTC, AndrewBarber reviewed
Updated maxInstances && minInstances

2022-07-19 10:59 UTC, S48-Mo approved these changes

2022-07-19 11:00 UTC, merged